name: Nickname Request
description: Request to add or change a player's nickname
title: "[Nickname] "
labels: ["nickname", "enhancement"]
body:
  - type: input
    id: player_name
    attributes:
      label: Player Name
      description: Player's name (English or Japanese)
      placeholder: "e.g., Shohei Ohtani / 大谷翔平"
    validations:
      required: true
  - type: input
    id: player_id
    attributes:
      label: Player ID (if known)
      description: lahmanID from the database
      placeholder: "e.g., ohtansh01"
    validations:
      required: false
  - type: input
    id: nickname
    attributes:
      label: Requested Nickname
      description: The nickname you want to add
      placeholder: "e.g., Shotime"
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason / Source
      description: Why this nickname? Any source or reference?
      placeholder: "This nickname is commonly used because..."
    validations:
      required: false
