name: Pitch Repertoire Submission
description: Submit pitch repertoires for pitchers
title: "[Pitch] "
labels: ["pitch-repertoire", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Pitch Repertoire Submission
        Submit pitcher repertoires!

        **Format:** `Player Name | Pitch1, Pitch2, Pitch3, ...`

        One pitcher per line. List pitches in order of usage (primary pitch first).

        **Available pitches:** Fastball, Slider, Curve, Changeup, Splitter, Forkball, Sinker, Cutter, Knuckleball, KnuckleCurve, CircleChange, Screwball
  - type: textarea
    id: pitches
    attributes:
      label: Pitch Repertoires
      description: "Format: Player Name | Pitch1, Pitch2, ... (one pitcher per line)"
      placeholder: |
        Yu Darvish | Fastball, Slider, Curve, Splitter, Changeup
        Masahiro Tanaka | Fastball, Splitter, Slider, Curve
        Shohei Ohtani | Fastball, Slider, Splitter, Curve
        Koji Uehara | Fastball, Splitter
      render: text
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      placeholder: "Any additional context (e.g., velocity, pitch nicknames)"
    validations:
      required: false
